// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgmxfjankqvjxvvleifr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnbXhmamFua3F2anh2dmxlaWZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTUyOTgsImV4cCI6MjA2MjI5MTI5OH0.HrG-dH2qyzSHeovRv_WLimPfJF83uWDPSE9SS0s7RxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);